package upgrad;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;

import java.sql.*;

public class Driver {

    /**
     * Driver class main method
     * @param args
     * @throws SQLException
     */
    public static void main(String[] args) {
        // MySql credentials

        // MongoDB Configurations

        // Connection Default Value Initialization
        Connection sqlConnection = null;
        MongoClient mongoClient = null;

        try {
            // Creating database connections

            // Import data into MongoDb

            // List all products in the inventory
            //CRUDHelper.displayAllProducts(collection);

            // Display top 5 Mobiles
            //CRUDHelper.displayTop5Mobiles(collection);

            // Display products ordered by their categories in Descending Order Without autogenerated Id
            //CRUDHelper.displayCategoryOrderedProductsDescending(collection);

            // Display product count in each category
            //CRUDHelper.displayProductCountByCategory(collection);

            // Display wired headphones
            //CRUDHelper.displayWiredHeadphones(collection);
        }
        catch(Exception ex) {
            System.out.println("Got Exception.");
            ex.printStackTrace();
        }
        finally {
            // Close Connections
        }
    }
}